# Generated by Django 2.0.2 on 2018-02-23 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataSearch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField(max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='client',
            name='department',
            field=models.CharField(blank=True, choices=[('---', '---'), ('1', 'IT'), ('2', 'Engineering'), ('3', 'Enterprise Analytics'), ('4', 'CGSO')], default='---', max_length=200, null=True, verbose_name='Departmnet Type'),
        ),
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='user_role',
            field=models.CharField(blank=True, choices=[('---', '---'), ('Admin', 'Admin'), ('publisher', 'Publisher'), ('consumer', 'Consumer')], default='---', max_length=200, null=True, verbose_name='User Role'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogpost', to='DataSearch.Client'),
        ),
    ]
