# Generated by Django 2.0.2 on 2018-02-23 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataSearch', '0002_auto_20180223_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='department',
            field=models.CharField(blank=True, choices=[('1', 'IT'), ('2', 'Engineering'), ('3', 'Enterprise Analytics'), ('4', 'CGSO')], default='---', max_length=200, null=True, verbose_name='Departmnet Type'),
        ),
        migrations.AlterField(
            model_name='client',
            name='user_role',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('publisher', 'Publisher'), ('consumer', 'Consumer')], default='---', max_length=200, null=True, verbose_name='User Role'),
        ),
    ]
