# Generated by Django 2.0.2 on 2018-02-26 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DataSearch', '0004_client_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='approved',
        ),
    ]
