# Generated by Django 2.0.2 on 2018-02-27 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataSearch', '0006_auto_20180226_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='user_role',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Publisher', 'Publisher'), ('Consumer', 'Consumer')], default='---', max_length=200, null=True, verbose_name='User Role'),
        ),
    ]
