# Generated by Django 2.0.2 on 2018-03-02 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataSearch', '0009_auto_20180301_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishserdata',
            name='inventory_ID',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='inventory_ID'),
        ),
        migrations.AddField(
            model_name='publishserdata',
            name='subdepartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_department_id', to='DataSearch.SubDepartment', verbose_name='sub_department_id'),
        ),
        migrations.AddField(
            model_name='subdepartment',
            name='code',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Code_values'),
        ),
        migrations.AlterField(
            model_name='publishserdata',
            name='dataset_come_from',
            field=models.CharField(choices=[('API connect', 'API connect'), ('Hadoop', 'Hadoop'), ('EDW', 'EDW'), ('Reltio', 'Reltio'), ('EODS', 'EODS'), ('Other', 'Other')], max_length=200, verbose_name='Sataset_Come_From'),
        ),
        migrations.AlterField(
            model_name='subdepartment',
            name='name',
            field=models.CharField(max_length=225, verbose_name='Sub_department'),
        ),
    ]
