# Generated by Django 2.0.2 on 2018-03-02 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataSearch', '0010_auto_20180302_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishserdata',
            name='data_classification_comments',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='classification_comment'),
        ),
        migrations.AlterField(
            model_name='publishserdata',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
