# Generated by Django 2.0.2 on 2018-03-05 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataSearch', '0011_auto_20180302_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='super_consumer',
            field=models.BooleanField(default=False),
        ),
    ]
