# Generated by Django 2.0.2 on 2018-03-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataSearch', '0013_auto_20180308_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishserdata',
            name='api_endpoint',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='API_Endpoint'),
        ),
        migrations.AlterField(
            model_name='publishserdata',
            name='category',
            field=models.CharField(blank=True, choices=[('Members', 'Members'), ('Providers', 'Providers'), ('Claims', 'Claims'), ('Care Management', 'Care Management'), ('Employers', ' Employers'), ('Agents', 'Agents'), ('Plans', 'Plans'), ('Customer Service', 'Customer Service')], max_length=200, null=True, verbose_name='category_type'),
        ),
    ]
