# Generated by Django 2.0 on 2018-03-19 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataSearch', '0015_auto_20180308_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishserdata',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publisher', to='DataSearch.Client'),
        ),
    ]
