# Generated by Django 2.0 on 2018-03-20 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataSearch', '0017_auto_20180320_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishserdata',
            name='dataset_come_from',
            field=models.CharField(choices=[('API connect', 'API connect'), ('Hadoop', 'Hadoop'), ('EDW', 'EDW'), ('Reltio', 'Reltio'), ('EODS', 'EODS'), ('Other', 'Other')], max_length=200, verbose_name='Sataset_Come_From'),
        ),
    ]
